version: '3.4'

services:
  gatewaydb:
    ports:
      - "5432:5432"

  gateway.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Information
      - Serilog__MinimumLevel__Override__System=Information

  banksimulator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development